/*
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
*/
#include <iostream>
#include "euler.h"
using namespace std;
void euler_p2() {
	const long long FOURMIL = 4000000;
	long long a=1,b=2,c=3;
	long long sum = 2;
	while (c < FOURMIL) {
		a = b;
		b = c;
		c = a + b;
		if ((c & 1) == 0)
			sum +=c;
	}
	cout << sum << endl;
}
